### ISSUE TITLE
Updating calorie intake in all recipes

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/octo-recipes#4]
Hey folks,

To keep up to modern days we really need to add the calorie intake to the recipes:
- [ ] [Oatmeal  Cookie](https://github.com/githubteacher/octo-recipes/blob/gh-pages/_posts/2014-09-10-oatmeal-cookie.md)
- [ ] [Quesadilla](https://github.com/githubteacher/octo-recipes/blob/gh-pages/_posts/2014-09-10-quesadilla.md)
- [ ] [Egg sandwich](https://github.com/githubteacher/octo-recipes/blob/gh-pages/_posts/2014-09-10-egg-sandwich.md)
- [ ] [French toast](https://github.com/githubteacher/octo-recipes/blob/gh-pages/_posts/2015-02-23-french-toast.md)

**Comment by bitoiu** [comment]
Everyone at DST4L said this is a terrible idea! We're dropping it.

**Comment by githubteacher** [comment]
ok, teacher approves :+1:
